<script>
 	$(document).ready(function() {
    	window.prettyPrint() && prettyPrint();
	});
 </script>


<form class="form-horizontal" id="projectForm" action="/index/update" method="post" role="form">
	<input type="hidden" id="project_id" name="project_id" value="<?=$this->project_id;?>">

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_txt">Project Name</label></h3>
		</div>
		<div class="panel-body">
			<input type="text" id="project_txt" name="project_txt" value="<?=$this->projects[0]['project_txt']?>" class="form-control" required>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_txt">Project Description</label></h3>
		</div>
		<div class="panel-body">
			<textarea rows="4" cols="50" id="project_desc" name="project_desc" class="form-control" required><?=$this->projects[0]['project_desc']?></textarea>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_txt">Project Lead</label></h3>
		</div>
		<div class="panel-body">
			<select name="project_lead"class="form-control">
				<option>Please select ...</option>
				<?php 
					foreach($this->team_members as $member) {
						$selected = ($member['user_id'] == $this->projects[0]['project_lead']) ? "selected" : "";
						echo "<option value='{$member['user_id']}' {$selected}>{$member['user_full_nm']}</option>\n";
					}
				?>
			</select>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_txt">Team Members</label></h3>
		</div>
		<div class="panel-body">
			<?php 
			function in_array_r($needle, $haystack, $strict = false) {
		    	foreach ($haystack as $item) {
		        	if (($strict ? $item === $needle : $item == $needle) || (is_array($item) && in_array_r($needle, $item, $strict))) {
		            	return true;
		        	}
		    	}
		    	return false;
			}
			?>
			<select id="s1" name="s1[]" multiple="multiple" class="form-control" data-role="multiselect">
				<?php 
				foreach($this->team_members as $member) {
					$selected = in_array_r($member['user_id'],$this->team_members_assigned) ? "selected" : "";
					echo "<option value='{$member['user_id']}' {$selected}>{$member['user_full_nm']}</option>\n";
				}
				?>
	    	</select>
		</div>
	</div>
	<div class="form-group">
		<div class=" col-lg-12">
			<input type="submit" value="Update" class="btn btn-success">
		</div>
	</div>
</form>
