<div class="table-responsive">
    <table  class="display table table-striped table-bordered" id="projects">
        <thead>
            <tr>
                <th nowrap="nowrap">Project Name</th>
                <th width="30%" class="hidden-xs hidden-sm">Description</th>
                <th nowrap="nowrap" class="">Project Lead</th>
                <th nowrap="nowrap" class="hidden-xs">Team Members</th>
                <th nowrap="nowrap">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->projects as $Row) { ?>
            <tr><?php $href=$this->url(array('controller'=>'index','action'=>'index','project_id'=>$Row['project_id']), null, TRUE); ?>
                <td nowrap="nowrap" style="vertical-align: top;">
                    <p>
                        <a title="Open Project" href="<?php echo $href ?>"><?php echo trim($Row['project_txt']); ?></a>
                    </p>
                </td>
                <td class="hidden-xs hidden-sm" style="vertical-align: top;">
                    <?php $description = $Row['project_desc']; ?>
                    <?php if (strlen($description) < 250): ?>
                      <div id="desc">
                            <?php echo nl2br(trim($description)); ?>
                        </div>
                    <?php else: ?>
                      <div class="panel-group" id="accordionDescription">
                        <div class="panel panel-default">
                          <div class="panel-heading">
                            <h4 class="panel-title">
                              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionDescription" href="#collapseDescription">
                                View Full Description
                              </a>
                            </h4>
                          </div>
                          <div id="collapseDescription" class="panel-collapse collapse">
                            <div class="panel-body">
                              <?php echo nl2br(trim($description)); ?>
                            </div>
                          </div>
                        </div>
                      </div>
                    <?php endif ?>
                </td>
                <td nowrap="nowrap" class="" style="vertical-align: top;">
                    <a title="Send Email" href="mailto:<?php echo (($Row['project_lead']!=null)?trim($Row['project_lead']['user_nm']):" "); ?>?subject=Regarding <?php echo trim($Row['project_txt']); ?>">
                        <?php echo (($Row['project_lead']!=null)?trim($Row['project_lead']['user_full_nm']):" "); ?>
                    </a> 
                </td>
                <td nowrap="nowrap" class="hidden-xs">
                    <?php
                        $i = 0;
                        $total_members = count($Row['team_members_assigned']);
                        if ($total_members > 6) : ?>
                            <div class="panel panel-default">
                              <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    View All <?php echo $total_members; ?> Members
                                  </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse">
                                <div class="panel-body">
                        <?php endif; ?>
                        <?php
                            foreach ( $Row ['team_members_assigned'] as $member ) :
                                echo "<a title=\"Send Email\" href=\"mailto: " . $member['user_nm'] . "?subject=Regarding ". trim($Row['project_txt']) . "\">" . $member['user_full_nm']."</a>" . ($i+1 < $total_members ? ', ' : '');
                                $i++; 
                                if ((($i % 3) == 0) && ($i != 0))
                                    echo "<br />";
                                endforeach; 
                        if ($total_members > 6) : ?>
                        </div>
                      </div>
                    </div>
                <?php endif; ?>
                </td>
                <td nowrap style="vertical-align: top;">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a title="View" href="<?php echo $href ?>"><i class="glyphicon glyphicon-eye-open"></i> View</a></li>
                          <?php if ($this->role=='administrator' || $this->role=='admin') { ?>
                            <li><a title="Edit" href="/index/edit/project_id/<?=$Row['project_id']?>"><i class="icon-pencil"></i> Edit</a></li>
                            <li><a title="Delete" href="/index/delete/project_id/<?=$Row['project_id']?>"
                            onclick="return confirm('WARNING! \n\nAre you sure you want to delete this project? \n\n')"><i class="icon-trash"></i> Delete</a></li>
                          <?php } ?>
                        </ul>
                    </div>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#projects').dataTable( {
      "bPaginate": false,
      "bSortClasses": false,
      "aaSorting": [],
      "sWrapper": "dataTables_wrapper form-inline"
      <?php if ($this->role=='administrator') { ?>
      ,"aoColumnDefs": [{ "asSorting": [  ], "aTargets": [ 4 ] }]
      <?php } ?>
    });
  });    
</script>