<script>
 	$(document).ready(function() {
    	window.prettyPrint() && prettyPrint();
	});
 </script>

<form class="form-horizontal" id="projectForm" action="/index/create" method="post" role="form">
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_txt">Project Name</label></h3>
		</div>
		<div class="panel-body">
			<input type="text" id="project_txt" name="project_txt" class="form-control" required>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_desc">Project Description</label></h3>
		</div>
		<div class="panel-body">
			<textarea rows="4" cols="50" id="project_desc" name="project_desc" class="form-control" required></textarea>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="project_lead">Project Lead</label></h3>
		</div>
		<div class="panel-body">
			<select name="project_lead" class="form-control" required>
				<option>Please select ...</option>
				<?php 
					foreach($this->team_members as $member) {
						echo "<option value='{$member['user_id']}'>{$member['user_full_nm']}</option>\n";
					}
				?>
			</select>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><label for="s1[]">Team Members</label></h3>
		</div>
		<div class="panel-body">
			<select id="s1" name="s1[]" multiple="multiple" class="form-control" data-role="multiselect">
			<?php 
				foreach($this->team_members as $member) {
					$selected = ($member['user_id'] == $this->projects[0]['project_lead']) ? "selected" : "";
					echo "<option value='{$member['user_id']}' {$selected}>{$member['user_full_nm']}</option>\n";
				}
			?>
			</select>
		</div>
	</div>

	<div class="form-group">
		<div class=" col-lg-12">
			<input type="submit" class="btn btn-success" value="Create">
		</div>
	</div>

</form>