<form  enctype="application/x-www-form-urlencoded" action="" method="post" class="form form-horizontal col-md-6 col-md-offset-3">

    <?php if ($this->message!='') {?>
    <div class="alert alert-danger">
    <?php echo $this->message; ?>
    </div>
    <?php } ?>
    <div class="form-group">
        <label for="email" class="col-lg-2 control-label">Email</label>
        <div class="col-lg-10">
            <input type="email" class="form-control" name="email" id="inputEmail1" placeholder="Email" autofocus="autofocus">
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-lg-2 control-label">Password</label>
        <div class="col-lg-10">
            <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?php echo $this->formSubmit("login","Login", array('class' => 'btn btn-success')); ?> 
            <?php echo $this->formSubmit("request_access","Request Access", array('class' => 'btn btn-default pull-right')); ?>
            <?php echo $this->formSubmit("reset_password","Reset Password", array('class' => 'btn btn-default pull-right')); ?>
        </div>
    </div>
    
</form>