<style>
/* Active row highlight color */
.slick-row.active .slick-cell {
     background-color: #FFB;
}

#toolbar {
	position:absolute; 
	top:0; 
	left:0; 
	height:1em;        /* toolbar is 1em high */
	width:100%;
	background-color: #f2f2f2;
	z-index:1000;			/* push our menu over the the #mainContent */
}

#grid_container {
	overflow:auto;      /* Let the scroll bars wrap the mainContent div not the body */
	position:absolute;   /* The mainBody is set in stone */
	top:1em;   			/* Start our mainContent below the header */
	left: 0px; 
	right:0px;  			/* This may not be right or needed */
	bottom:2em;        /* This may not be right or needed */
	width:100%;
	/*z-index:1;*/
}

#statusbar {
	overflow:hidden; 
	position:absolute; 
	bottom:0; 
	left:0; 
	height:2em;        /* Footer is 10px high */
	width:100%;
	background-color: #f2f2f2;
	z-index:0;
	border-top: 1px solid rgb(231, 231, 231);
}

</style>

<div id="grid_wrapper" style="">
  <div id="toolbar">
    test
  </div>
  <div id="grid_container">
    <?php echo $this->PHPSlickGrid($this->grid,null,'height:100%;'); ?>
  </div>
  <div id="statusbar">
    <div id="statusbar_left" class="col-md-4">
		Footer Left
	</div>
	<div class="col-md-4 text-center hidden-xs hidden-sm"> 
		Center
	</div>
	<div id="footer_right" class="col-md-4 text-right pull-right">
		Footer Right
	</div>
  </div>
</div>
