<br /><br />
<div id="view-content">
    <div>
        <p>this->user</p>
        <p><pre><?php echo print_r($this->user,true); ?></pre></p>
    </div>
    <div>
        <p>this->acl</p>
        <p><pre><?php echo print_r($this->acl,true); ?></pre></p>
    </div>
    <div>
	    <p>this->navigation</p>
	    <p><pre><?php echo print_r($this->navigation->toArray(),true); ?></pre></p>
	</div>
	<div>
	    <p>this->applications</p>
	    <p><pre><?php echo print_r($this->applications->toArray(),true); ?></pre></p>
	</div>
	<div>
	    <p>this->app</p>
	    <p><pre><?php echo print_r($this->app->toArray(),true); ?></pre></p>
	</div>
	<div>
	    <p>this->customers</p>
	    <p><pre><?php echo print_r($this->customers,true); ?></pre></p>
	</div>
	<div>
	    <p>this->current_customer</p>
	    <p><pre><?php echo print_r($this->current_customer->toArray(),true); ?></pre></p>
	</div>
	<div>
	    <p>this->user_role</p>
	    <p><pre><?php echo print_r($this->user_role->toArray(),true); ?></pre></p>
	</div>
	<div>
	    <p>this->config</p>
	    <p><pre><?php echo print_r($this->config->toArray(),true); ?></pre></p>
	</div>
</div>